version: "3.7"
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    networks:
      - app-tier
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    hostname: localhost
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    networks:
      - app-tier
    depends_on:
      - zookeeper

  producer:
    image: stea1th/kafka-producer:latest
    container_name: kafka-producer
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - app-tier
    ports:
      - 8082:8082
    depends_on:
      - kafka

  consumer:
    image: stea1th/kafka-consumer:latest
    container_name: kafka-consumer
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - app-tier
    ports:
      - 8081:8081
    depends_on:
      - kafka

networks:
  app-tier:
    driver: bridge

