version: "3.7"
services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      #      KAFKA_ADVERTISED_PORT: 9092
      #      KAFKA_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      #      KAFKA_HOST: localhost
      #      KAFKA_PORT: 9092
      #      KAFKA_ADVERTISED_HOST_NAME: localhost
      #      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
#      KAFKA_CREATE_TOPICS: "server.pizza:1:1"
    depends_on:
      - zookeeper

#  server:
#    image: stea1th/kafka-server:latest
#    container_name: kafka-server
#    environment:
#      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
#    #    build: .
#    #    networks:
#    #      - kafka-network
#    ports:
#      - 8081:8081
#
#  client:
#    image: stea1th/kafka-test:latest
#    container_name: kafka-client
#    environment:
#      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
#    #    build: ./kafka-pilot-test
#    #    networks:
#    #      - kafka-network
#    ports:
#      - 8082:8082
#    depends_on:
#      - server


#networks:
#  default:
#    external:
#      name: bridge
#  kafka-network:
